'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="convserum")>  _
Partial Public Class DataClasses1DataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.serum.My.MySettings.Default.convserumConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.conv_serum1")>  _
	Public Function conv_serum1(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="Int")> ByVal visit_id As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="VarChar(50)")> ByVal fname As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="VarChar(50)")> ByVal jname As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="VarChar(50)")> ByVal lname As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="Date")> ByVal dtp_dob As System.Nullable(Of Date), <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="VarChar(50)")> ByVal ftype As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="Date")> ByVal dtp_int As System.Nullable(Of Date), <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="Date")> ByVal dtp_expected As System.Nullable(Of Date), <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="VarChar(50)")> ByVal conv_taken As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="VarChar(50)")> ByVal cmb_ifno As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="VarChar(50)")> ByVal txt_other As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="Date")> ByVal dtp_convserum As System.Nullable(Of Date), <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="VarChar(50)")> ByVal lbl_serum As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="VarChar(50)")> ByVal dss As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="TinyInt")> ByVal type As System.Nullable(Of Byte)) As ISingleResult(Of conv_serum1Result)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), visit_id, fname, jname, lname, dtp_dob, ftype, dtp_int, dtp_expected, conv_taken, cmb_ifno, txt_other, dtp_convserum, lbl_serum, dss, type)
		Return CType(result.ReturnValue,ISingleResult(Of conv_serum1Result))
	End Function
End Class

Partial Public Class conv_serum1Result
	
	Private _visit_id As Integer
	
	Private _fname As String
	
	Private _jname As String
	
	Private _lname As String
	
	Private _dtp_dob As System.Nullable(Of Date)
	
	Private _ftype As String
	
	Private _dtp_int As System.Nullable(Of Date)
	
	Private _dtp_expected As System.Nullable(Of Date)
	
	Private _conv_taken As String
	
	Private _cmb_ifno As String
	
	Private _txt_other As String
	
	Private _dtp_convserum As Date
	
	Private _lbl_serum As String
	
	Private _dss As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_visit_id", DbType:="Int NOT NULL")>  _
	Public Property visit_id() As Integer
		Get
			Return Me._visit_id
		End Get
		Set
			If ((Me._visit_id = value)  _
						= false) Then
				Me._visit_id = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fname", DbType:="VarChar(50)")>  _
	Public Property fname() As String
		Get
			Return Me._fname
		End Get
		Set
			If (String.Equals(Me._fname, value) = false) Then
				Me._fname = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_jname", DbType:="VarChar(50)")>  _
	Public Property jname() As String
		Get
			Return Me._jname
		End Get
		Set
			If (String.Equals(Me._jname, value) = false) Then
				Me._jname = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lname", DbType:="VarChar(50)")>  _
	Public Property lname() As String
		Get
			Return Me._lname
		End Get
		Set
			If (String.Equals(Me._lname, value) = false) Then
				Me._lname = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dtp_dob", DbType:="Date")>  _
	Public Property dtp_dob() As System.Nullable(Of Date)
		Get
			Return Me._dtp_dob
		End Get
		Set
			If (Me._dtp_dob.Equals(value) = false) Then
				Me._dtp_dob = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ftype", DbType:="VarChar(10)")>  _
	Public Property ftype() As String
		Get
			Return Me._ftype
		End Get
		Set
			If (String.Equals(Me._ftype, value) = false) Then
				Me._ftype = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dtp_int", DbType:="Date")>  _
	Public Property dtp_int() As System.Nullable(Of Date)
		Get
			Return Me._dtp_int
		End Get
		Set
			If (Me._dtp_int.Equals(value) = false) Then
				Me._dtp_int = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dtp_expected", DbType:="Date")>  _
	Public Property dtp_expected() As System.Nullable(Of Date)
		Get
			Return Me._dtp_expected
		End Get
		Set
			If (Me._dtp_expected.Equals(value) = false) Then
				Me._dtp_expected = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_conv_taken", DbType:="VarChar(10)")>  _
	Public Property conv_taken() As String
		Get
			Return Me._conv_taken
		End Get
		Set
			If (String.Equals(Me._conv_taken, value) = false) Then
				Me._conv_taken = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cmb_ifno", DbType:="VarChar(100)")>  _
	Public Property cmb_ifno() As String
		Get
			Return Me._cmb_ifno
		End Get
		Set
			If (String.Equals(Me._cmb_ifno, value) = false) Then
				Me._cmb_ifno = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txt_other", DbType:="VarChar(150)")>  _
	Public Property txt_other() As String
		Get
			Return Me._txt_other
		End Get
		Set
			If (String.Equals(Me._txt_other, value) = false) Then
				Me._txt_other = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dtp_convserum", DbType:="Date NOT NULL")>  _
	Public Property dtp_convserum() As Date
		Get
			Return Me._dtp_convserum
		End Get
		Set
			If ((Me._dtp_convserum = value)  _
						= false) Then
				Me._dtp_convserum = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lbl_serum", DbType:="VarChar(50)")>  _
	Public Property lbl_serum() As String
		Get
			Return Me._lbl_serum
		End Get
		Set
			If (String.Equals(Me._lbl_serum, value) = false) Then
				Me._lbl_serum = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dss", DbType:="VarChar(50)")>  _
	Public Property dss() As String
		Get
			Return Me._dss
		End Get
		Set
			If (String.Equals(Me._dss, value) = false) Then
				Me._dss = value
			End If
		End Set
	End Property
End Class
